/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontSize: {
        xs: '13px',
      },
    },
  },
  plugins: [
    require('tailwind-scrollbar-hide'),
    require('@tailwindcss/typography'),
    require('daisyui'),
  ],

  daisyui: {
    styled: true,
    themes: [{
      light: {
        ...require("daisyui/src/colors/themes")["[data-theme=light]"],
        "--rounded-box": "0.5rem",
        "--rounded-btn": "0.5rem",
        "--rounded-badge": "0.375rem",
        "--tab-radius": "0.5rem",
        "primary": "#FB7299",
        "primary-content": "#FFFFFF",
        "secondary": "#00AEEC",
        "secondary-content": "#FFFFFF",
        "accent": "#FF8CB1",
        "accent-content": "#FFFFFF",
        "neutral": "#2F3238",
        "neutral-content": "#FFFFFF",
        "base-100": "#FFFFFF",
        "base-200": "#F6F7F8",
        "base-300": "#E3E5E7",
        "base-content": "#18191C",
        "info": "#00AEEC",
        "info-content": "#FFFFFF",
        "success": "#2BC840",
        "success-content": "#FFFFFF",
        "warning": "#FFB84D",
        "warning-content": "#4A3200",
        "error": "#FF5C7A",
        "error-content": "#FFFFFF",
      },
    }, {
      dark: {
        ...require("daisyui/src/colors/themes")["[data-theme=dark]"],
        "--rounded-box": "0.5rem",
        "--rounded-btn": "0.5rem",
        "--rounded-badge": "0.375rem",
        "--tab-radius": "0.5rem",
        "primary": "#FB7299",
        "primary-content": "#2B1019",
        "secondary": "#00AEEC",
        "secondary-content": "#07141C",
        "accent": "#C95A7F",
        "accent-content": "#FFEAF1",
        "neutral": "#21242B",
        "neutral-content": "#E3E5E7",
        "base-100": "#171A21",
        "base-200": "#0F1115",
        "base-300": "#2A2F3A",
        "base-content": "#E3E5E7",
        "info": "#33C0F3",
        "info-content": "#041018",
        "success": "#43D25A",
        "success-content": "#071A0B",
        "warning": "#FFB84D",
        "warning-content": "#2D1D00",
        "error": "#FF6E8A",
        "error-content": "#2A0E16",
      }
    }],
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: "",
    darkTheme: "dark",
  },
}
